runtime: nodejs20

instance_class: F2

env_variables:
  MONGODB_USERNAME: "KeeperAdmin001"
  MONGODB_PASSWORD: "JKyTeOfZIKjspOGn"
  JWT_TOKEN_KEY: "h6tdfvgnfgvcxfnn"


handlers:
  url: /. *
  secure: always
  redirect_http_response_code: 301
  script: auto